general:

  startup_commands: ['shell-exec zebar' , 'shell-exec glazewm-extra']
  shutdown_commands: ['shell-exec taskkill /IM zebar.exe /F']

  focus_follows_cursor: false
  toggle_workspace_on_refocus: false
  
  cursor_jump:
    enabled: false
    trigger: 'window_focus'

  hide_method: "hide"
  show_all_in_taskbar: false
  
  
gaps:

  inner_gap: '5px'
  
  outer_gap: 
    top: '5px'
    right: '5px'
    bottom: '5px'
    left: '5px'


window_effects:

  focused_window:
    border:
      enabled: true
      color: '#11181d'

  other_windows:
    border:
      enabled: true
      color: '#11181d'

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: 'tiling'

  # Sets the default options for when a new window is created. This also
  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true

      # Whether to show floating windows as always on top.
      shown_on_top: true

    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false

      # Whether to show fullscreen windows as always on top.
      shown_on_top: false

workspaces:
  - name: '1'
  - name: '2'
  - name: '3'
  - name: '4'
  - name: '5'
  - name: '6'
  - name: '7'
  - name: '8'
  - name: '9'

window_rules:

  - commands: ['move --workspace 2' , 'focus --workspace 2']
    match:
      - window_process: { equals: 'ArmCord'}

  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
      - window_process: { equals: 'GHelper' }
      - window_process: { equals: 'bf1' }
      - window_process: { equals: 'TslGame' }
      - window_process: { equals: 'hl2' }
      - window_process: { equals: 'NeedForSpeedUnbound' }
      - window_process: { equals: 'Titanfall2'}

binding_modes:

  # When enabled, all keybindings are disabled except for alt+shift+p which
  # returns to default keybindings.
  - name: 'pause'
    keybindings:
      - commands: ['wm-disable-binding-mode --name pause']
        bindings: ['alt+shift+p']
        
      - commands: ['wm-enable-binding-mode --name pause']
        bindings: ['alt+shift+p']

keybindings:


  # Shift focus in a given direction.
  - commands: ['focus --direction left']
    bindings: ['alt+left']
  - commands: ['focus --direction right']
    bindings: ['alt+right']
  - commands: ['focus --direction up']
    bindings: ['alt+up']
  - commands: ['focus --direction down']
    bindings: ['alt+down']


  # Move focused window in a given direction.
  - commands: ['move --direction left']
    bindings: ['alt+shift+left']
  - commands: ['move --direction right']
    bindings: ['alt+shift+right']
  - commands: ['move --direction up']
    bindings: ['alt+shift+up']
  - commands: ['move --direction down']
    bindings: ['alt+shift+down']

  # Change tiling direction. This determines where new tiling windows will
  # be inserted.
  - commands: ['toggle-tiling-direction']
    bindings: ['alt+w']

  # Change focus from tiling windows -> floating -> fullscreen.
  - commands: ['wm-cycle-focus']
    bindings: ['alt+space']

  # Change the focused window to be floating.
  - commands: ['toggle-floating --centered']
    bindings: ['alt+shift+space']

  # Change the focused window to be tiling.
  #- commands: ['toggle-tiling']
  #  bindings: ['alt+t']

  # Change the focused window to be fullscreen.
  - commands: ['toggle-fullscreen']
    bindings: ['lwin+f']

  # Minimize focused window.
  - commands: ['toggle-minimized']
    bindings: ['lwin+m']

  # Close focused window.
  - commands: ['close']
    bindings: ['lwin+q']

  # Kill GlazeWM process safely.
  - commands: ['wm-exit']
    bindings: ['alt+shift+e']

  # Re-evaluate configuration file.
  - commands: ['wm-reload-config']
    bindings: ['alt+shift+r']

  # Redraw all windows.
  - commands: ['wm-redraw']
    bindings: ['alt+shift+w']

   
  # Change focus to a workspace defined in `workspaces` config.
  - commands: ['focus --workspace 1']
    bindings: ['lwin+1']
  - commands: ['focus --workspace 2']
    bindings: ['lwin+2']
  - commands: ['focus --workspace 3']
    bindings: ['lwin+3']
  - commands: ['focus --workspace 4']
    bindings: ['lwin+4']
  - commands: ['focus --workspace 5']
    bindings: ['lwin+5']
  - commands: ['focus --workspace 6']
    bindings: ['lwin+6']
  - commands: ['focus --workspace 7']
    bindings: ['lwin+7']
  - commands: ['focus --workspace 8']
    bindings: ['lwin+8']
  - commands: ['focus --workspace 9']
    bindings: ['lwin+9']



  # Move focused window to a workspace defined in `workspaces` config.
  - commands: ['move --workspace 1', 'focus --workspace 1']
    bindings: ['lwin+shift+1']
  - commands: ['move --workspace 2', 'focus --workspace 2']
    bindings: ['lwin+shift+2']
  - commands: ['move --workspace 3', 'focus --workspace 3']
    bindings: ['lwin+shift+3']
  - commands: ['move --workspace 4', 'focus --workspace 4']
    bindings: ['lwin+shift+4']
  - commands: ['move --workspace 5', 'focus --workspace 5']
    bindings: ['lwin+shift+5']
  - commands: ['move --workspace 6', 'focus --workspace 6']
    bindings: ['lwin+shift+6']
  - commands: ['move --workspace 7', 'focus --workspace 7']
    bindings: ['lwin+shift+7']
  - commands: ['move --workspace 8', 'focus --workspace 8']
    bindings: ['lwin+shift+8']
  - commands: ['move --workspace 9', 'focus --workspace 9']
    bindings: ['lwin+shift+9']
    
    
    # Keybinds
    

  - commands: ['shell-exec brave']
    bindings: ['lwin+b']
    
  - commands: ['shell-exec zen']
    bindings: ['lwin+z']

  - commands: ['shell-exec wt']
    bindings: ['lwin+enter']

  - commands: ['shell-exec C:\ProgramData\Microsoft\Windows\Start Menu\Programs\VS Code.lnk']
    bindings: ['alt+v']

  - commands: ['shell-exec explorer.exe C:\Games\Oyunlar']
    bindings: ['alt+g']

  - commands: ['shell-exec C:\Users\Alfendow\.glzr\glazewm\config.yaml']
    bindings: ['alt+shift+c']

  - commands: ['shell-exec explorer.exe C:\ProgramData\Microsoft\Windows\Start Menu\Programs']
    bindings: ['alt+shift+a']

  - commands: ['shell-exec shell:RecycleBinFolder']
    bindings: ['lwin+g']

  - commands: ['shell-exec C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Control Panel.lnk']
    bindings: ['lwin+c']
    
  - commands: ['shell-exec C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Aygıt Yöneticisi.lnk']
    bindings: ['lwin+a']
    
  - commands: ['shell-exec C:\Users\Alfendow\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Obsidian.lnk']
    bindings: ['alt+shift+o']
    
  - commands: ['shell-exec C:\Users\Alfendow\Documents\Ders Programı\Ders Programı.pdf']
    bindings: ['alt+shift+d']
    
  - commands: ['shell-exec C:\Users\Alfendow\Documents\Ders Programı\Sınav Takvimi.pdf']
    bindings: ['alt+shift+s']
    
  - commands: ['shell-exec C:\Users\Alfendow\.glzr\zebar\starter\styles.css']
    bindings: ['alt+shift+x']
    
  - commands: ['shell-exec glazewm-extra']
    bindings: ['alt+x']
