watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 30
    padding:
      top: 5
      left: 5
      bottom: 5
      right: 5
    widgets:
      left: ["glazewm_workspaces","taskbar"]
      center: ["clock"]
      right: ["systray","volume","power_menu"]
      
      
widgets:

  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: ""
      label_expanded: ""
      label_position: "left"
      icon_size: 16
      pin_click_modifier: "alt" 
      show_unpinned: false
      show_battery: false
      show_volume: false
      show_network: true


  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 15


  glazewm_workspaces:
    type: "glazewm.workspaces.GlazewmWorkspacesWidget"
    options:
      offline_label: "GlazeWM Offline"
      hide_empty_workspaces: true
      hide_if_offline: false
      

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: ""
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{  %d %B %A     %H:%M }"
      locale: "tr"
      calendar:
        border_color: "#fdb9c6"
        alignment: "center"
        offset_top: 10
        
        
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 250 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          sleep: ["\u23fe", "Uyku"]
          restart: ["\uead2", "Yeniden Başlat"]
          shutdown: ["\uf011", "Kapat"]
          cancel: ["󰌍", "Geri"]
