# Rules are applied to every window once it is created.
[[window_rules]]
command = "set title false"
match_process_name = "notepad++|ArmCord|WinRAR|qbittorrent|Code|Telegram"

# Rules are applied to the focused window when the focus changes.
[[focused_window_rules]]
command = "set translucent 220"
match_process_name = "Spotify|notepad++|Discord|Obsidian|ArmCord|WinRAR|qbittorrent|Telegram"


# Rules are applied to the unfocused windows when the focus changes.
#[[unfocused_window_rules]]
#command = "set translucent 50"
#match_process_name = ".*"